-- Redirects table
CREATE TABLE IF NOT EXISTS seo_redirects (
    id VARCHAR(255) NOT NULL PRIMARY KEY,
    from_pattern VARCHAR(500) NOT NULL,
    to_url VARCHAR(500) NOT NULL,
    type VARCHAR(3) DEFAULT '301',
    is_active BOOLEAN DEFAULT TRUE,
    hit_count INT DEFAULT 0,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    created_by VARCHAR(255) NULL
);

-- 404 Logs table
CREATE TABLE IF NOT EXISTS seo_404_logs (
    id VARCHAR(255) NOT NULL PRIMARY KEY,
    url VARCHAR(500) NOT NULL UNIQUE,
    referer VARCHAR(500) NULL,
    user_agent TEXT NULL,
    hit_count INT DEFAULT 1,
    last_seen DATETIME DEFAULT CURRENT_TIMESTAMP,
    first_seen DATETIME DEFAULT CURRENT_TIMESTAMP
);

-- Robots columns in posts
ALTER TABLE posts ADD COLUMN IF NOT EXISTS robots_index BOOLEAN DEFAULT TRUE;
ALTER TABLE posts ADD COLUMN IF NOT EXISTS robots_follow BOOLEAN DEFAULT TRUE;
ALTER TABLE posts ADD COLUMN IF NOT EXISTS robots_advanced VARCHAR(200) NULL;
