-- Add missing SEO columns to posts table
ALTER TABLE posts 
ADD COLUMN IF NOT EXISTS readability_score INT DEFAULT 0,
ADD COLUMN IF NOT EXISTS keyword_density DECIMAL(5,4) DEFAULT 0,
ADD COLUMN IF NOT EXISTS schema_data JSON NULL,
ADD COLUMN IF NOT EXISTS enabled_schema_types JSON NULL,
ADD COLUMN IF NOT EXISTS robots_index BOOLEAN DEFAULT TRUE,
ADD COLUMN IF NOT EXISTS robots_follow BOOLEAN DEFAULT TRUE,
ADD COLUMN IF NOT EXISTS robots_advanced VARCHAR(200) NULL,
ADD COLUMN IF NOT EXISTS breadcrumb_title VARCHAR(255) NULL,
ADD COLUMN IF NOT EXISTS faq_items JSON NULL,
ADD COLUMN IF NOT EXISTS how_to_steps JSON NULL;
